// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: post_tags.sql

package post_tags

import (
	"context"
)

const createPostTag = `-- name: CreatePostTag :one
INSERT INTO post_tags (
  postid, tagid
) VALUES (
  $1,$2
)
RETURNING id, postid, tagid
`

type CreatePostTagParams struct {
	Postid int32
	Tagid  int32
}

type CreatePostTagRow struct {
	ID     int32
	Postid int32
	Tagid  int32
}

func (q *Queries) CreatePostTag(ctx context.Context, arg CreatePostTagParams) (CreatePostTagRow, error) {
	row := q.db.QueryRowContext(ctx, createPostTag, arg.Postid, arg.Tagid)
	var i CreatePostTagRow
	err := row.Scan(&i.ID, &i.Postid, &i.Tagid)
	return i, err
}

const deletePostTag = `-- name: DeletePostTag :exec
DELETE FROM post_tags
WHERE postid = $1
`

func (q *Queries) DeletePostTag(ctx context.Context, postid int32) error {
	_, err := q.db.ExecContext(ctx, deletePostTag, postid)
	return err
}
