// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package user

import (
	"database/sql"
)

type Post struct {
	ID          int32
	Userid      int32
	Title       string
	Description string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type PostTag struct {
	ID        int32
	Postid    int32
	Tagid     int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Tag struct {
	ID        int32
	Tagname   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type User struct {
	ID        int32
	Fullname  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
